### PR TITLE
add ALKIS s/w map

### LINKED ISSUE #12: Greyscale ALKIS layer
In the FIS Broker there is a b/w version of the ALKIS map, is it possible to access this version over the mapproxy?

### PR DESCRIPTION
**Pull request by karlbeecken**
fixes #12

Adds the ALKIS s/w (black & white) version to the config

### CODE REVIEW

**Comment by tordans** [comment]
Hi @karlbeecken we could do that, yes. I am a bit hesitant since both versions are super similar and will use up the same resources (disc space, processing time). Would your usecase allow to apply a grayscale css effect on the colored layer, which should result in a similar result. For example like this https://github.com/zlant/parking-lanes/search?q=mapnik_gray

**Comment by karlbeecken** [comment]
Hi, my usecase is using the tiles as a base layer in uMap, so as far as I can tell that isn't easily possible. Also the gray layer provided by the FIS Broker has better contrast than just grayscaling the colored one (e.g. the trees are a very light green, that would result in a light gray grayscaled version – the native gray map however has the trees black). How many ressources would you estimate to be needed? Maybe I can just host it myself?

**Comment by tordans** [comment]
We can add the layer and see how it goes.

> How many ressources would you estimate to be needed? Maybe I can just host it myself?

There is probably a way to calculate that but I don't know how. It depends on your bbox and how many zoom levels you want to support. 

You could try setting up this project locally https://github.com/codeforberlin/mapproxy-config#install and do a test. That would also help with testing the zoom 20-issue. I don't never had a local instance running.

**Comment by jochenklar** [comment]
It should be relatively easy to set up locally if you have Linux, a Mac or the subsystem for linux on a Windows machine.

**Comment by karlbeecken** [comment]
I tried setting it up on an Ubuntu  20.04 server yesterday according to the manual in the README, and it runs without error messages, but every tile returned is just a white png. Instance is running under https://umap.dmho.de/proxy/

**Comment by tordans** [comment]
> …I tried setting it up on an Ubuntu 20.04 server yesterday according to the manual in the README, and it runs without error messages, but every tile returned is just a white png. Instance is running under https://umap.dmho.de/proxy/

It does work (now), looking at https://supaplexosm.github.io/strassenraumkarte-neukoelln/mapproxy_demo_map.html?url=https://umap.dmho.de/proxy/tiles/1.0.0/alkis_30/mercator/{z}/{x}/{y}.png#18/52.48209/13.44155 and an example image at https://umap.dmho.de/proxy/tiles/1.0.0/alkis_30/mercator/18/140860/86018.png.

In case you only looked at the demo URL https://umap.dmho.de/proxy/demo/ – that does not work out of the box, no idea why.

---

It would be great if you played around with more settings to see if you get the zoom issue solved! There are a few debugging tips at https://github.com/codeforberlin/mapproxy-config#remeber-to-delete-the-file-system-cache.

**Comment by tordans** [comment]
Should we still merge this PR or are you planning on using your own instance?

**Comment by karlbeecken** [comment]
Hi, I managed to get my instance working with the s/w version and even zoom up to level 24 (apparently mapproxy needs a bit of time to be able to serve previously unconfigured tiles). So I can run my own instance, no merge required.

What could be interesting for #14 and #11 is the fact that mapproxy doesn't immediately respect changes in configuration, so @tordans attempt with just setting the `num_levels` to 22 wasn't wrong  – it just needs time.

**Comment by tordans** [comment]
@karlbeecken could you share your config at https://github.com/karlbeecken/mapproxy-config/; I would then try again getting the zoom fixed.

> needs time

So I would restart the proxy with the new config, delete the cache and then wait for a night (~10 h) before testing?

**Comment by karlbeecken** [comment]
See https://github.com/karlbeecken/mapproxy-config/commit/7d9a79682d3079e0f9f6a81a8ae7db5e48f213f5 for my config.

I installed the proxy wednesday evening and apparently today in the morning it worked – but I installed the whole proxy, changing the num_levels shouldn't take that long. I think your plan looks fine

**Pull request closed without merging**
